### ISSUE TITLE
Change the number of retry

### ISSUE THREAD

**Issue by diorcety** [Nextdoor/tornado_rest_client#9]
I maybe misunderstand the documentation but I see no way to change the number of retry. Is it true?

**Comment by diranged** [comment]
I think you are correct - I did not expose a way to customize that. Patches welcome. This project is still used heavily by some of our tools, but we have obviously not needed to contribute to it very much.

**Comment by diorcety** [comment]
One solution could be to remove the retry decorator on fetch and let the user create an function in a subclass with the decorator on this function in order to let him choose the number of retry.
